version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service

  add-service:
    build: ./addition
    hostname: add-service
    ports:
      - 5051:5051  # host:container
    volumes:
      - ./addition/app:/app
    depends_on:
      - landing-service                             
    networks:
      sample:
        aliases:
          - add-service

  minus-service:
    build: ./subtraction
    hostname: minus-service
    ports:
      - 5052:5052  # host:container
    volumes:
      - ./subtraction/app:/app
    depends_on:
      - landing-service                             
    networks:
      sample:
        aliases:
          - minus-service

  multiply-service:
    build: ./multiplication
    hostname: multiply-service
    ports:
      - 5053:5053  # host:container
    volumes:
      - ./multiplication/app:/app
    depends_on:
      - landing-service                             
    networks:
      sample:
        aliases:
          - multiply-service

  divide-service:
    build: ./division
    hostname: divide-service
    ports:
      - 5054:5054  # host:container
      volumes:
      - ./division/app:/app
    depends_on:
      - landing-service                             
    networks:
      sample:
        aliases:
          - divide-service
  gcd-service:
    build: ./gcd
    hostname: gcd-service
    ports:
      - 5055:5055  # host:container
    volumes:
      - ./gcd/app:/app
    depends_on:
      - landing-service                             
    networks:
      sample:
        aliases:
          - gcd-service
  lcm-service:
    build: ./lcm
    hostname: lcm-service
    ports:
      - 5056:5056  # host:container
    volumes:
      - ./lcm/app:/app
    depends_on:
      - landing-service  
      - gcd-service                           
    networks:
      sample:
        aliases:
          - lcm-service
  modulus-service:
    build: ./modulus
    hostname: modulus-service
    ports:
      - 5057:5057  # host:container
    volumes:
      - ./modulus/app:/app
    depends_on:
      - landing-service                         
    networks:
      sample:
        aliases:
          - modulus-service
  exponent-service:
    build: ./exponent
    hostname: exponent-service
    ports:
      - 5058:5058  # host:container
      volumes:
      - ./exponent/app:/app
    depends_on:
      - landing-service                         
    networks:
      sample:
        aliases:
          - exponent-service
  greater-than-service:
    build: ./greater_than
    hostname: greater-than-service
    ports:
      - 5059:5059  # host:container
    volumes:
      - ./greater_than/app:/app
    depends_on:
      - landing-service                         
    networks:
      sample:
        aliases:
          - greater-than-service
  lesser-than-service:
    build: ./lesser_than
    hostname: lesser-than-service
    ports:
      - 5060:5060  # host:container
    volumes:
      - ./lesser_than/app:/app
    depends_on:
      - landing-service                         
    networks:
      sample:
        aliases:
          - lesser-than-service
  equal-service:
    build: ./equal
    hostname: equal-than-service
    ports:
      - 5061:5061  # host:container
    volumes:
      - ./equal/app:/app
    depends_on:
      - landing-service                         
    networks:
      sample:
        aliases:
          - equal-service
networks:
  sample:
